export enum PlacesActions {
  SET_USER_LOCATION = 'SET_USER_LOCATION',
  SET_PLACES = 'SET_PLACES',
  SET_SEARCH_QUERY = 'SET_SEARCH_QUERY',
  SET_SEARCHING_PLACES = 'SET_SEARCHING_PLACES',
}

export enum MapActions {
  SET_MAP = 'SET_MAP',
}
